cache:
  directories:
    - $HOME/.cache/pip
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"  
install: pip install tox-travis
script: tox

before_install:
  - pip install codecov

after_success:
  - codecov

notifications:
  email: false
